// Auto-generated by the Load Impact converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "LED Control ON",
    id: "bfeb084a-d6de-49ea-98f5-e2d198d3e4a7",
    method: "GET",
    address: "http://127.0.0.1:8000/led_on"
  });

  postman[Request]({
    name: "LED Control OFF",
    id: "dd8ac7bf-0503-4655-bb88-17b0d7b77b63",
    method: "GET",
    address: "http://127.0.0.1:8000/led_off"
  });

  postman[Request]({
    name: "DOOR Control Open",
    id: "ce507cff-90f1-4368-bf40-21cae04bf1ec",
    method: "GET",
    address: "http://127.0.0.1:8000/door_on"
  });

  postman[Request]({
    name: "DOOR Control Close",
    id: "87321558-dbbc-49b4-b8c9-771f79646831",
    method: "GET",
    address: "http://127.0.0.1:8000/door_off"
  });

  postman[Request]({
    name: "Electrictiy Bill Regressor",
    id: "46433f0d-e754-4dc9-b1d8-52b10b0628e0",
    method: "GET",
    address: "http://127.0.0.1:8000/electricity_bill"
  });

  postman[Request]({
    name: "Video HTTP Streaming",
    id: "821e3af1-4deb-4255-9c82-17d09e64d761",
    method: "GET",
    address: "http://127.0.0.1:3002"
  });

  postman[Request]({
    name: "Adding User",
    id: "9f43984c-3fdf-437b-b8a3-895db701cffd",
    method: "POST",
    address: "http://127.0.0.1:8888/loginAuthentication",
    data:
      '  {\n            "username": "user1",\n            "password": "98f325e67"\n        }'
  });
}
